//
//  EmotionManager.swift
//  QSwift
//
//  Created by DongJin on 2021/8/28.
//

import Foundation
import QKeyboardEmotionView

class EmotionManager: NSObject {
    
    static let shared: EmotionManager = EmotionManager()
    
    //禁止别的地方初始化本类
    fileprivate override init() {
        super.init()
    }
    
    public lazy var emotionArray: [QEmotion] = {
        var emotionArray = [QEmotion]()
        emotionArray.append(QEmotion(identifier: "Expression_1", displayName: "[微笑]"))
        emotionArray.append(QEmotion(identifier: "Expression_2", displayName: "[撇嘴]"))
        emotionArray.append(QEmotion(identifier: "Expression_3", displayName: "[色]"))
        emotionArray.append(QEmotion(identifier: "Expression_4", displayName: "[发呆]"))
        emotionArray.append(QEmotion(identifier: "Expression_5", displayName: "[得意]"))
        emotionArray.append(QEmotion(identifier: "Expression_6", displayName: "[流泪]"))
        emotionArray.append(QEmotion(identifier: "Expression_7", displayName: "[害羞]"))
        emotionArray.append(QEmotion(identifier: "Expression_8", displayName: "[闭嘴]"))
        emotionArray.append(QEmotion(identifier: "Expression_9", displayName: "[睡]"))
        emotionArray.append(QEmotion(identifier: "Expression_10", displayName: "[大哭]"))
        emotionArray.append(QEmotion(identifier: "Expression_11", displayName: "[尴尬]"))
        emotionArray.append(QEmotion(identifier: "Expression_12", displayName: "[发怒]"))
        emotionArray.append(QEmotion(identifier: "Expression_13", displayName: "[调皮]"))
        emotionArray.append(QEmotion(identifier: "Expression_14", displayName: "[呲牙]"))
        emotionArray.append(QEmotion(identifier: "Expression_15", displayName: "[惊讶]"))
        emotionArray.append(QEmotion(identifier: "Expression_16", displayName: "[难过]"))
        emotionArray.append(QEmotion(identifier: "Expression_17", displayName: "[酷]"))
        emotionArray.append(QEmotion(identifier: "Expression_18", displayName: "[冷汗]"))
        emotionArray.append(QEmotion(identifier: "Expression_19", displayName: "[抓狂]"))
        emotionArray.append(QEmotion(identifier: "Expression_20", displayName: "[吐]"))
        emotionArray.append(QEmotion(identifier: "Expression_101", displayName: "[嘿哈]"))
        emotionArray.append(QEmotion(identifier: "Expression_102", displayName: "[奸笑]"))
        emotionArray.append(QEmotion(identifier: "Expression_103", displayName: "[捂脸]"))
        emotionArray.append(QEmotion(identifier: "Expression_104", displayName: "[机智]"))
        emotionArray.append(QEmotion(identifier: "Expression_105", displayName: "[皱眉]"))
        emotionArray.append(QEmotion(identifier: "Expression_106", displayName: "[耶]"))
        emotionArray.append(QEmotion(identifier: "Expression_107", displayName: "[红包]"))
        emotionArray.append(QEmotion(identifier: "Expression_108", displayName: "[蜡烛]"))
        emotionArray.append(QEmotion(identifier: "Expression_109", displayName: "[小鸡]"))
        emotionArray.append(QEmotion(identifier: "Expression_110", displayName: "[旺柴]"))
        emotionArray.append(QEmotion(identifier: "Watermelon", displayName: "[吃瓜]"))
        emotionArray.append(QEmotion(identifier: "Addoil", displayName: "[加油]"))
        emotionArray.append(QEmotion(identifier: "Sweat", displayName: "[汗]"))
        emotionArray.append(QEmotion(identifier: "Shocked", displayName: "[天啊]"))
        emotionArray.append(QEmotion(identifier: "Cold", displayName: "[Emm]"))
        emotionArray.append(QEmotion(identifier: "Social", displayName: "[社会]"))
        emotionArray.append(QEmotion(identifier: "NoProb", displayName: "[好的]"))
        emotionArray.append(QEmotion(identifier: "Slap", displayName: "[打脸]"))
        emotionArray.append(QEmotion(identifier: "Boring", displayName: "[翻白眼]"))
        emotionArray.append(QEmotion(identifier: "KeepFighting", displayName: "[加油加油]"))
        emotionArray.append(QEmotion(identifier: "666", displayName: "[666]"))
        emotionArray.append(QEmotion(identifier: "LetMeSee", displayName: "[我看看]"))
        emotionArray.append(QEmotion(identifier: "Sigh", displayName: "[叹气]"))
        emotionArray.append(QEmotion(identifier: "Hurt", displayName: "[苦涩]"))
        emotionArray.append(QEmotion(identifier: "Broken", displayName: "[裂开]"))
        emotionArray.append(QEmotion(identifier: "Expression_21", displayName: "[偷笑]"))
        emotionArray.append(QEmotion(identifier: "Expression_23", displayName: "[白眼]"))
        emotionArray.append(QEmotion(identifier: "Expression_24", displayName: "[傲慢]"))
        emotionArray.append(QEmotion(identifier: "Expression_25", displayName: "[饥饿]"))
        emotionArray.append(QEmotion(identifier: "Expression_26", displayName: "[困]"))
        emotionArray.append(QEmotion(identifier: "Expression_27", displayName: "[惊恐]"))
        emotionArray.append(QEmotion(identifier: "Expression_28", displayName: "[流汗]"))
        emotionArray.append(QEmotion(identifier: "Expression_29", displayName: "[憨笑]"))
        emotionArray.append(QEmotion(identifier: "Expression_30", displayName: "[悠闲]"))
        emotionArray.append(QEmotion(identifier: "Expression_31", displayName: "[奋斗]"))
        emotionArray.append(QEmotion(identifier: "Expression_32", displayName: "[咒骂]"))
        emotionArray.append(QEmotion(identifier: "Expression_33", displayName: "[疑问]"))
        emotionArray.append(QEmotion(identifier: "Expression_34", displayName: "[嘘]"))
        emotionArray.append(QEmotion(identifier: "Expression_35", displayName: "[晕]"))
        emotionArray.append(QEmotion(identifier: "Expression_36", displayName: "[疯了]"))
        emotionArray.append(QEmotion(identifier: "Expression_37", displayName: "[衰]"))
        emotionArray.append(QEmotion(identifier: "Expression_38", displayName: "[骷髅]"))
        emotionArray.append(QEmotion(identifier: "Expression_39", displayName: "[敲打]"))
        emotionArray.append(QEmotion(identifier: "Expression_40", displayName: "[再见]"))
        emotionArray.append(QEmotion(identifier: "Expression_41", displayName: "[擦汗]"))
        emotionArray.append(QEmotion(identifier: "Expression_42", displayName: "[抠鼻]"))
        emotionArray.append(QEmotion(identifier: "Expression_43", displayName: "[鼓掌]"))
        emotionArray.append(QEmotion(identifier: "Expression_44", displayName: "[坏笑]"))
        emotionArray.append(QEmotion(identifier: "Expression_45", displayName: "[糗大了]"))
        emotionArray.append(QEmotion(identifier: "Expression_46", displayName: "[左哼哼]"))
        emotionArray.append(QEmotion(identifier: "Expression_47", displayName: "[右哼哼]"))
        emotionArray.append(QEmotion(identifier: "Expression_48", displayName: "[哈欠]"))
        emotionArray.append(QEmotion(identifier: "Expression_49", displayName: "[鄙视]"))
        emotionArray.append(QEmotion(identifier: "Expression_50", displayName: "[委屈]"))
        emotionArray.append(QEmotion(identifier: "Expression_51", displayName: "[快哭了]"))
        emotionArray.append(QEmotion(identifier: "Expression_52", displayName: "[阴险]"))
        emotionArray.append(QEmotion(identifier: "Expression_53", displayName: "[亲亲]"))
        emotionArray.append(QEmotion(identifier: "Expression_54", displayName: "[吓]"))
        emotionArray.append(QEmotion(identifier: "Expression_55", displayName: "[可怜]"))
        emotionArray.append(QEmotion(identifier: "Expression_56", displayName: "[菜刀]"))
        emotionArray.append(QEmotion(identifier: "Expression_57", displayName: "[西瓜]"))
        emotionArray.append(QEmotion(identifier: "Expression_58", displayName: "[啤酒]"))
        emotionArray.append(QEmotion(identifier: "Expression_59", displayName: "[篮球]"))
        emotionArray.append(QEmotion(identifier: "Expression_60", displayName: "[乒乓]"))
        emotionArray.append(QEmotion(identifier: "Expression_61", displayName: "[咖啡]"))
        emotionArray.append(QEmotion(identifier: "Expression_62", displayName: "[饭]"))
        emotionArray.append(QEmotion(identifier: "Expression_63", displayName: "[猪头]"))
        emotionArray.append(QEmotion(identifier: "Expression_64", displayName: "[玫瑰]"))
        emotionArray.append(QEmotion(identifier: "Expression_65", displayName: "[凋谢]"))
        emotionArray.append(QEmotion(identifier: "Expression_66", displayName: "[嘴唇]"))
        emotionArray.append(QEmotion(identifier: "Expression_67", displayName: "[爱心]"))
        emotionArray.append(QEmotion(identifier: "Expression_68", displayName: "[心碎]"))
        emotionArray.append(QEmotion(identifier: "Expression_69", displayName: "[蛋糕]"))
        emotionArray.append(QEmotion(identifier: "Expression_70", displayName: "[闪电]"))
        emotionArray.append(QEmotion(identifier: "Expression_71", displayName: "[炸弹]"))
        emotionArray.append(QEmotion(identifier: "Expression_72", displayName: "[刀]"))
        emotionArray.append(QEmotion(identifier: "Expression_73", displayName: "[足球]"))
        emotionArray.append(QEmotion(identifier: "Expression_74", displayName: "[瓢虫]"))
        emotionArray.append(QEmotion(identifier: "Expression_75", displayName: "[便便]"))
        emotionArray.append(QEmotion(identifier: "Expression_76", displayName: "[月亮]"))
        emotionArray.append(QEmotion(identifier: "Expression_77", displayName: "[太阳]"))
        emotionArray.append(QEmotion(identifier: "Expression_78", displayName: "[礼物]"))
        emotionArray.append(QEmotion(identifier: "Expression_79", displayName: "[拥抱]"))
        emotionArray.append(QEmotion(identifier: "Expression_80", displayName: "[强]"))
        emotionArray.append(QEmotion(identifier: "Expression_81", displayName: "[弱]"))
        emotionArray.append(QEmotion(identifier: "Expression_82", displayName: "[握手]"))
        emotionArray.append(QEmotion(identifier: "Expression_83", displayName: "[胜利]"))
        emotionArray.append(QEmotion(identifier: "Expression_84", displayName: "[抱拳]"))
        emotionArray.append(QEmotion(identifier: "Expression_85", displayName: "[勾引]"))
        emotionArray.append(QEmotion(identifier: "Expression_86", displayName: "[拳头]"))
        emotionArray.append(QEmotion(identifier: "Expression_87", displayName: "[差劲]"))
        emotionArray.append(QEmotion(identifier: "Expression_88", displayName: "[爱你]"))
        emotionArray.append(QEmotion(identifier: "Expression_89", displayName: "[NO]"))
        emotionArray.append(QEmotion(identifier: "Expression_90", displayName: "[OK]"))
        emotionArray.append(QEmotion(identifier: "Expression_91", displayName: "[爱情]"))
        
        for emotion in emotionArray{
            emotion.image = UIImage.init(named: emotion.identifier)
        }
        
        return emotionArray
    }()
    
}
